name: srirnn_jax
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - flax==0.8.3
    - fsspec==2024.5.0
    - importlib-resources==6.4.0
    - jsonargparse==4.29.0
    - librosa==0.10.2.post1
    - matplotlib==3.9.0
    - pandas==2.2.2

